// Generated by ego.
// DO NOT EDIT

//line homeSidePanel.ego:1

package components

import "fmt"
import "html"
import "io"
import "context"

import "github.com/blavkboy/matcha/models"

func HomeSidePanel(w io.Writer, u *models.User) {

//line homeSidePanel.ego:8
	_, _ = io.WriteString(w, "\n<nav class=\"panel\">\n  <p class=\"panel-heading\">\n    Welcome ")
//line homeSidePanel.ego:10
	fmt.Fprint(w, u.Username)
//line homeSidePanel.ego:11
	_, _ = io.WriteString(w, "\n  </p>\n  <p class=\"panel-block\">\n    <span class=\"panel-icon\" style=\"color: orangered;\">\n      <i class=\"fas fa-fire\"></i>\n    </span>\n    Fame rating:\n  </p>\n  <p class=\"panel-block\">\n    <span class=\"panel-icon\" style=\"color: red;\">\n      <i class=\"fas fa-heart\"></i>\n    </span>\n    Likes: \n  </p>\n  <p class=\"panel-block\">\n    <span class=\"panel-icon\">\n      <i class=\"far fa-eye\"></i>\n    </span>\n    Vists: \n  </p>\n</nav>\n")
//line homeSidePanel.ego:31
}

var _ fmt.Stringer
var _ io.Reader
var _ context.Context
var _ = html.EscapeString
