// Generated by ego.
// DO NOT EDIT

//line head.ego:1

package views

import "fmt"
import "html"
import "io"
import

//line head.ego:6
"context"

func ProduceHead(w io.Writer) {

	_, _ = io.WriteString(w, "\n<link rel=\"stylesheet\" type=\"text/css\" href=\"http://localhost:8080/static/custom.css\">\n<title>My Site</title>\n")
//line head.ego:8
}

var _ fmt.Stringer
var _ io.Reader
var _ context.Context
var _ = html.EscapeString
