// Generated by ego.
// DO NOT EDIT

//line views/head.ego:1

package views

import "fmt"
import "html"
import "io"
import

//line views/head.ego:6
"context"

func ProduceHead(w io.Writer) {

	_, _ = io.WriteString(w, "\n<meta charset=\"utf-8\">\n<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n<meta name=\"viewport\" content=\"width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no\">\n\n<meta name=\"description\" content=\"a dating app\">\n<meta name=\"author\" content=\"blavkboy\">\n<title>My Site</title>\n\n<link rel=\"stylesheet\" type=\"text/css\" href=\"http://localhost:8080/static/css/bootstrap.min.css\">\n<link rel=\"stylesheet\" type=\"text/css\" href=\"http://localhost:8080/static/css/custom.css\">\n\n<script src=\"http://localhost:8080/static/js/jquery-3.3.1.min.js\"></script>\n<script src=\"http://localhost:8080/static/js/bootstrap.min.js\"></script>\n\n<link href=\"https://fonts.googleapis.com/css?family=Fruktur\" rel=\"stylesheet\">\n<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->\n<!--[if lt IE 9]>\n  <script src=\"https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js\"></script>\n  <script src=\"https://oss.maxcdn.com/respond/1.4.2/respond.min.js\"></script>\n<![endif]-->\n")
//line views/head.ego:26
}

var _ fmt.Stringer
var _ io.Reader
var _ context.Context
var _ = html.EscapeString
