// Generated by ego.
// DO NOT EDIT

//line views/home.ego:1

package views

import "fmt"
import "html"
import "io"
import "context"

import "github.com/blavkboy/matcha/views/components/headers"
import "github.com/blavkboy/matcha/views/components"
import "github.com/blavkboy/matcha/models"

func RenderHome(w io.Writer, u *models.User) {

//line views/home.ego:10
	_, _ = io.WriteString(w, "\n<head>\n")
//line views/home.ego:11

	produceHead(w, headers.HomeStyles, headers.HomeScripts)

//line views/home.ego:14
	_, _ = io.WriteString(w, "\n</head>\n<body style=\"height:100%; width:100%;\">\n  ")
//line views/home.ego:16

	components.HomeNavbar(w, u)

//line views/home.ego:19
	_, _ = io.WriteString(w, "\n  <div class=\"columns\"> \n    <div class=\"column is-one-quarter\">\n      ")
//line views/home.ego:21

	components.HomeSidePanel(w, u)

//line views/home.ego:24
	_, _ = io.WriteString(w, "\n    </div>\n    <div class=\"column is-three-quarter\">\n      <div class=\"container\" id=\"main_column\" style=\"grid-row: 1; grid-column: 1;\">\n        <img src=\"http://localhost:8080/static/defaultpic.jpg\" alt=\"profile picture\">\n        <div style=\"grid-row:2; grid-column: 2;\">\n        Hello\n        </div>\n      </div>\n    </div>\n  </div>\n</body>\n")
//line views/home.ego:35
}

var _ fmt.Stringer
var _ io.Reader
var _ context.Context
var _ = html.EscapeString
